### ISSUE TITLE
Using other ESP features?

### ISSUE THREAD

**Issue by Violet-Vibes** [themaoci/NLog-Example-CheatBase#1]
Hey. Successfully compiled it but I'm a bit confused how I enable stuff like ExilESP etc.

Any hints?

**Comment by themaoci** [comment]
https://github.com/themaoci/NLog-Example-CheatBase/blob/master/Menu.cs#L76
add here a switch for other things
https://github.com/themaoci/NLog-Example-CheatBase/blob/master/Instance.cs#L56
add Update here
https://github.com/themaoci/NLog-Example-CheatBase/blob/master/Instance.cs#L62
add Drawing here

**Comment by Violet-Vibes** [comment]
Figured it out, thanks! I only added the exits, as I'm horrible with the
maps and haven't learned all of them yet, so just having the exits is a
huge help.

Again, thanks.

**Comment by themaoci** [comment]
good you found what you need :) i will close that issue

**Comment by Violet-Vibes** [comment]
any ideas how to improve the drawing of esp stuff? seems its very "poor" compared to the previous version, flickers, draws things out of focus/view, etc
